# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 700)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frameimport = QtWidgets.QFrame(self.centralwidget)
        self.frameimport.setGeometry(QtCore.QRect(10, 10, 211, 161))
        self.frameimport.setFrameShape(QtWidgets.QFrame.Box)
        self.frameimport.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameimport.setLineWidth(3)
        self.frameimport.setObjectName("frameimport")
        self.importlabel = QtWidgets.QLabel(self.frameimport)
        self.importlabel.setGeometry(QtCore.QRect(10, 10, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(True)
        self.importlabel.setFont(font)
        self.importlabel.setObjectName("importlabel")
        self.importf1 = QtWidgets.QRadioButton(self.frameimport)
        self.importf1.setGeometry(QtCore.QRect(10, 50, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.importf1.setFont(font)
        self.importf1.setIconSize(QtCore.QSize(16, 16))
        self.importf1.setChecked(True)
        self.importf1.setObjectName("importf1")
        self.spicebtn = QtWidgets.QPushButton(self.frameimport)
        self.spicebtn.setGeometry(QtCore.QRect(120, 40, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spicebtn.setFont(font)
        self.spicebtn.setStyleSheet("background-color: rgb(235, 235, 235);\n"
" border-style: solid;\n"
" border-width:5px;\n"
" border-color: rgb(220, 220, 220);")
        self.spicebtn.setAutoDefault(False)
        self.spicebtn.setDefault(False)
        self.spicebtn.setFlat(False)
        self.spicebtn.setObjectName("spicebtn")
        self.importf2 = QtWidgets.QRadioButton(self.frameimport)
        self.importf2.setGeometry(QtCore.QRect(10, 70, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.importf2.setFont(font)
        self.importf2.setIconSize(QtCore.QSize(16, 16))
        self.importf2.setChecked(False)
        self.importf2.setObjectName("importf2")
        self.importf3 = QtWidgets.QRadioButton(self.frameimport)
        self.importf3.setGeometry(QtCore.QRect(10, 90, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.importf3.setFont(font)
        self.importf3.setIconSize(QtCore.QSize(16, 16))
        self.importf3.setChecked(False)
        self.importf3.setObjectName("importf3")
        self.digilentbtn = QtWidgets.QPushButton(self.frameimport)
        self.digilentbtn.setGeometry(QtCore.QRect(120, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.digilentbtn.setFont(font)
        self.digilentbtn.setStyleSheet("background-color: rgb(235, 235, 235);\n"
" border-style: solid;\n"
" border-width:5px;\n"
" border-color: rgb(220, 220, 220);")
        self.digilentbtn.setAutoDefault(False)
        self.digilentbtn.setDefault(False)
        self.digilentbtn.setFlat(False)
        self.digilentbtn.setObjectName("digilentbtn")
        self.probebtn = QtWidgets.QPushButton(self.frameimport)
        self.probebtn.setGeometry(QtCore.QRect(120, 120, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.probebtn.setFont(font)
        self.probebtn.setStyleSheet("background-color: rgb(235, 235, 235);\n"
" border-style: solid;\n"
" border-width:5px;\n"
" border-color: rgb(220, 220, 220);")
        self.probebtn.setAutoDefault(False)
        self.probebtn.setDefault(False)
        self.probebtn.setFlat(False)
        self.probebtn.setObjectName("probebtn")
        self.importf4 = QtWidgets.QRadioButton(self.frameimport)
        self.importf4.setGeometry(QtCore.QRect(10, 110, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.importf4.setFont(font)
        self.importf4.setIconSize(QtCore.QSize(16, 16))
        self.importf4.setChecked(False)
        self.importf4.setObjectName("importf4")
        self.importf5 = QtWidgets.QRadioButton(self.frameimport)
        self.importf5.setGeometry(QtCore.QRect(10, 130, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.importf5.setFont(font)
        self.importf5.setIconSize(QtCore.QSize(16, 16))
        self.importf5.setChecked(False)
        self.importf5.setObjectName("importf5")
        self.frametransfer = QtWidgets.QFrame(self.centralwidget)
        self.frametransfer.setGeometry(QtCore.QRect(230, 10, 571, 161))
        self.frametransfer.setFrameShape(QtWidgets.QFrame.Box)
        self.frametransfer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frametransfer.setLineWidth(3)
        self.frametransfer.setObjectName("frametransfer")
        self.transferencialabel = QtWidgets.QLabel(self.frametransfer)
        self.transferencialabel.setGeometry(QtCore.QRect(10, 10, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(True)
        self.transferencialabel.setFont(font)
        self.transferencialabel.setLineWidth(3)
        self.transferencialabel.setObjectName("transferencialabel")
        self.line = QtWidgets.QFrame(self.frametransfer)
        self.line.setGeometry(QtCore.QRect(310, 90, 251, 20))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.numerator = QtWidgets.QLabel(self.frametransfer)
        self.numerator.setGeometry(QtCore.QRect(315, 66, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(16)
        self.numerator.setFont(font)
        self.numerator.setAlignment(QtCore.Qt.AlignCenter)
        self.numerator.setObjectName("numerator")
        self.transferf1 = QtWidgets.QRadioButton(self.frametransfer)
        self.transferf1.setGeometry(QtCore.QRect(10, 50, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.transferf1.setFont(font)
        self.transferf1.setIconSize(QtCore.QSize(16, 16))
        self.transferf1.setChecked(True)
        self.transferf1.setObjectName("transferf1")
        self.transferf3 = QtWidgets.QRadioButton(self.frametransfer)
        self.transferf3.setGeometry(QtCore.QRect(10, 90, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.transferf3.setFont(font)
        self.transferf3.setIconSize(QtCore.QSize(16, 16))
        self.transferf3.setChecked(False)
        self.transferf3.setObjectName("transferf3")
        self.transferf2 = QtWidgets.QRadioButton(self.frametransfer)
        self.transferf2.setGeometry(QtCore.QRect(10, 70, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.transferf2.setFont(font)
        self.transferf2.setIconSize(QtCore.QSize(16, 16))
        self.transferf2.setChecked(False)
        self.transferf2.setObjectName("transferf2")
        self.coefvalue = QtWidgets.QTextEdit(self.frametransfer)
        self.coefvalue.setGeometry(QtCore.QRect(190, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.coefvalue.setFont(font)
        self.coefvalue.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.coefvalue.setFrameShape(QtWidgets.QFrame.Box)
        self.coefvalue.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.coefvalue.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.coefvalue.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.coefvalue.setReadOnly(False)
        self.coefvalue.setObjectName("coefvalue")
        self.coeforder = QtWidgets.QTextEdit(self.frametransfer)
        self.coeforder.setGeometry(QtCore.QRect(130, 80, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.coeforder.setFont(font)
        self.coeforder.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.coeforder.setFrameShape(QtWidgets.QFrame.Box)
        self.coeforder.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.coeforder.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.coeforder.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.coeforder.setReadOnly(False)
        self.coeforder.setObjectName("coeforder")
        self.denominator = QtWidgets.QLabel(self.frametransfer)
        self.denominator.setGeometry(QtCore.QRect(315, 106, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(16)
        self.denominator.setFont(font)
        self.denominator.setAlignment(QtCore.Qt.AlignCenter)
        self.denominator.setObjectName("denominator")
        self.acceptequation = QtWidgets.QPushButton(self.frametransfer)
        self.acceptequation.setGeometry(QtCore.QRect(310, 10, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.acceptequation.setFont(font)
        self.acceptequation.setStyleSheet("background-color: rgb(235, 235, 235);\n"
" border-style: solid;\n"
" border-width:5px;\n"
" border-color: rgb(220, 220, 220);")
        self.acceptequation.setAutoDefault(False)
        self.acceptequation.setDefault(False)
        self.acceptequation.setFlat(False)
        self.acceptequation.setObjectName("acceptequation")
        self.eraseequation = QtWidgets.QPushButton(self.frametransfer)
        self.eraseequation.setGeometry(QtCore.QRect(490, 10, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.eraseequation.setFont(font)
        self.eraseequation.setStyleSheet("background-color: rgb(235, 235, 235);\n"
" border-style: solid;\n"
" border-width:5px;\n"
" border-color: rgb(220, 220, 220);")
        self.eraseequation.setAutoDefault(False)
        self.eraseequation.setDefault(False)
        self.eraseequation.setFlat(False)
        self.eraseequation.setObjectName("eraseequation")
        self.transferf4 = QtWidgets.QRadioButton(self.frametransfer)
        self.transferf4.setGeometry(QtCore.QRect(10, 110, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.transferf4.setFont(font)
        self.transferf4.setIconSize(QtCore.QSize(16, 16))
        self.transferf4.setChecked(False)
        self.transferf4.setObjectName("transferf4")
        self.transferf5 = QtWidgets.QRadioButton(self.frametransfer)
        self.transferf5.setGeometry(QtCore.QRect(10, 130, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.transferf5.setFont(font)
        self.transferf5.setIconSize(QtCore.QSize(16, 16))
        self.transferf5.setChecked(False)
        self.transferf5.setObjectName("transferf5")
        self.label = QtWidgets.QLabel(self.frametransfer)
        self.label.setGeometry(QtCore.QRect(130, 50, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frametransfer)
        self.label_2.setGeometry(QtCore.QRect(190, 50, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.addcoefficient = QtWidgets.QPushButton(self.frametransfer)
        self.addcoefficient.setGeometry(QtCore.QRect(120, 120, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addcoefficient.setFont(font)
        self.addcoefficient.setStyleSheet("background-color: rgb(235, 235, 235);\n"
" border-style: solid;\n"
" border-width:5px;\n"
" border-color: rgb(220, 220, 220);")
        self.addcoefficient.setAutoDefault(False)
        self.addcoefficient.setDefault(False)
        self.addcoefficient.setFlat(False)
        self.addcoefficient.setObjectName("addcoefficient")
        self.frameplotconfig = QtWidgets.QFrame(self.centralwidget)
        self.frameplotconfig.setGeometry(QtCore.QRect(810, 10, 461, 161))
        self.frameplotconfig.setFrameShape(QtWidgets.QFrame.Box)
        self.frameplotconfig.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameplotconfig.setLineWidth(3)
        self.frameplotconfig.setObjectName("frameplotconfig")
        self.importlabel_2 = QtWidgets.QLabel(self.frameplotconfig)
        self.importlabel_2.setGeometry(QtCore.QRect(10, 10, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(True)
        self.importlabel_2.setFont(font)
        self.importlabel_2.setObjectName("importlabel_2")
        self.saveamp = QtWidgets.QPushButton(self.frameplotconfig)
        self.saveamp.setGeometry(QtCore.QRect(300, 40, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.saveamp.setFont(font)
        self.saveamp.setStyleSheet("background-color: rgb(235, 235, 235);\n"
" border-style: solid;\n"
" border-width:5px;\n"
" border-color: rgb(220, 220, 220);")
        self.saveamp.setAutoDefault(False)
        self.saveamp.setDefault(False)
        self.saveamp.setFlat(False)
        self.saveamp.setObjectName("saveamp")
        self.savephase = QtWidgets.QPushButton(self.frameplotconfig)
        self.savephase.setGeometry(QtCore.QRect(300, 80, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.savephase.setFont(font)
        self.savephase.setStyleSheet("background-color: rgb(235, 235, 235);\n"
" border-style: solid;\n"
" border-width:5px;\n"
" border-color: rgb(220, 220, 220);")
        self.savephase.setAutoDefault(False)
        self.savephase.setDefault(False)
        self.savephase.setFlat(False)
        self.savephase.setObjectName("savephase")
        self.saveboth = QtWidgets.QPushButton(self.frameplotconfig)
        self.saveboth.setGeometry(QtCore.QRect(300, 120, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.saveboth.setFont(font)
        self.saveboth.setStyleSheet("background-color: rgb(235, 235, 235);\n"
" border-style: solid;\n"
" border-width:5px;\n"
" border-color: rgb(220, 220, 220);")
        self.saveboth.setAutoDefault(False)
        self.saveboth.setDefault(False)
        self.saveboth.setFlat(False)
        self.saveboth.setObjectName("saveboth")
        self.importlabel_3 = QtWidgets.QLabel(self.frameplotconfig)
        self.importlabel_3.setGeometry(QtCore.QRect(300, 10, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(True)
        self.importlabel_3.setFont(font)
        self.importlabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.importlabel_3.setObjectName("importlabel_3")
        self.checkf5 = QtWidgets.QCheckBox(self.frameplotconfig)
        self.checkf5.setGeometry(QtCore.QRect(20, 130, 121, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkf5.setFont(font)
        self.checkf5.setObjectName("checkf5")
        self.checkf3 = QtWidgets.QCheckBox(self.frameplotconfig)
        self.checkf3.setGeometry(QtCore.QRect(20, 90, 131, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkf3.setFont(font)
        self.checkf3.setObjectName("checkf3")
        self.checkf1 = QtWidgets.QCheckBox(self.frameplotconfig)
        self.checkf1.setGeometry(QtCore.QRect(20, 50, 131, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkf1.setFont(font)
        self.checkf1.setObjectName("checkf1")
        self.checkf4 = QtWidgets.QCheckBox(self.frameplotconfig)
        self.checkf4.setGeometry(QtCore.QRect(20, 110, 121, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkf4.setFont(font)
        self.checkf4.setObjectName("checkf4")
        self.checkf2 = QtWidgets.QCheckBox(self.frameplotconfig)
        self.checkf2.setGeometry(QtCore.QRect(20, 70, 121, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkf2.setFont(font)
        self.checkf2.setObjectName("checkf2")
        self.importlabel_4 = QtWidgets.QLabel(self.frameplotconfig)
        self.importlabel_4.setGeometry(QtCore.QRect(160, 30, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(True)
        self.importlabel_4.setFont(font)
        self.importlabel_4.setObjectName("importlabel_4")
        self.checkp1 = QtWidgets.QCheckBox(self.frameplotconfig)
        self.checkp1.setGeometry(QtCore.QRect(180, 50, 16, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkp1.setFont(font)
        self.checkp1.setText("")
        self.checkp1.setObjectName("checkp1")
        self.checkp2 = QtWidgets.QCheckBox(self.frameplotconfig)
        self.checkp2.setGeometry(QtCore.QRect(180, 70, 16, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkp2.setFont(font)
        self.checkp2.setText("")
        self.checkp2.setObjectName("checkp2")
        self.checkp3 = QtWidgets.QCheckBox(self.frameplotconfig)
        self.checkp3.setGeometry(QtCore.QRect(180, 90, 16, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkp3.setFont(font)
        self.checkp3.setText("")
        self.checkp3.setObjectName("checkp3")
        self.checkp4 = QtWidgets.QCheckBox(self.frameplotconfig)
        self.checkp4.setGeometry(QtCore.QRect(180, 110, 16, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkp4.setFont(font)
        self.checkp4.setText("")
        self.checkp4.setObjectName("checkp4")
        self.checkp5 = QtWidgets.QCheckBox(self.frameplotconfig)
        self.checkp5.setGeometry(QtCore.QRect(180, 130, 16, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkp5.setFont(font)
        self.checkp5.setText("")
        self.checkp5.setObjectName("checkp5")
        self.importlabel_6 = QtWidgets.QLabel(self.frameplotconfig)
        self.importlabel_6.setGeometry(QtCore.QRect(220, 30, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(True)
        self.importlabel_6.setFont(font)
        self.importlabel_6.setAlignment(QtCore.Qt.AlignCenter)
        self.importlabel_6.setObjectName("importlabel_6")
        self.origin1 = QtWidgets.QLabel(self.frameplotconfig)
        self.origin1.setGeometry(QtCore.QRect(220, 50, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.origin1.setFont(font)
        self.origin1.setAlignment(QtCore.Qt.AlignCenter)
        self.origin1.setObjectName("origin1")
        self.origin2 = QtWidgets.QLabel(self.frameplotconfig)
        self.origin2.setGeometry(QtCore.QRect(220, 70, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.origin2.setFont(font)
        self.origin2.setAlignment(QtCore.Qt.AlignCenter)
        self.origin2.setObjectName("origin2")
        self.origin3 = QtWidgets.QLabel(self.frameplotconfig)
        self.origin3.setGeometry(QtCore.QRect(220, 90, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.origin3.setFont(font)
        self.origin3.setAlignment(QtCore.Qt.AlignCenter)
        self.origin3.setObjectName("origin3")
        self.origin4 = QtWidgets.QLabel(self.frameplotconfig)
        self.origin4.setGeometry(QtCore.QRect(220, 110, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.origin4.setFont(font)
        self.origin4.setAlignment(QtCore.Qt.AlignCenter)
        self.origin4.setObjectName("origin4")
        self.origin5 = QtWidgets.QLabel(self.frameplotconfig)
        self.origin5.setGeometry(QtCore.QRect(220, 130, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.origin5.setFont(font)
        self.origin5.setAlignment(QtCore.Qt.AlignCenter)
        self.origin5.setObjectName("origin5")
        self.frameplot = QtWidgets.QFrame(self.centralwidget)
        self.frameplot.setGeometry(QtCore.QRect(10, 180, 1261, 511))
        self.frameplot.setFrameShape(QtWidgets.QFrame.Box)
        self.frameplot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameplot.setLineWidth(3)
        self.frameplot.setObjectName("frameplot")
        self.ampplot = QtWidgets.QWidget(self.frameplot)
        self.ampplot.setGeometry(QtCore.QRect(10, 10, 611, 491))
        self.ampplot.setObjectName("ampplot")
        self.phaseplot = QtWidgets.QWidget(self.frameplot)
        self.phaseplot.setGeometry(QtCore.QRect(640, 10, 611, 491))
        self.phaseplot.setObjectName("phaseplot")
        self.frameplotconfig.raise_()
        self.frametransfer.raise_()
        self.frameimport.raise_()
        self.frameplot.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.importlabel.setText(_translate("MainWindow", "Importar Datos"))
        self.importf1.setText(_translate("MainWindow", "Función 1"))
        self.spicebtn.setText(_translate("MainWindow", "SPICE"))
        self.importf2.setText(_translate("MainWindow", "Función 2"))
        self.importf3.setText(_translate("MainWindow", "Función 3"))
        self.digilentbtn.setText(_translate("MainWindow", "Digilent"))
        self.probebtn.setText(_translate("MainWindow", "CSV"))
        self.importf4.setText(_translate("MainWindow", "Función 4"))
        self.importf5.setText(_translate("MainWindow", "Función 5"))
        self.transferencialabel.setText(_translate("MainWindow", "Ecuación de Transferencia"))
        self.numerator.setText(_translate("MainWindow", "0"))
        self.transferf1.setText(_translate("MainWindow", "Función 1"))
        self.transferf3.setText(_translate("MainWindow", "Función 3"))
        self.transferf2.setText(_translate("MainWindow", "Función 2"))
        self.coefvalue.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.coeforder.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.denominator.setText(_translate("MainWindow", "0"))
        self.acceptequation.setText(_translate("MainWindow", "Aceptar"))
        self.eraseequation.setText(_translate("MainWindow", "Borrar"))
        self.transferf4.setText(_translate("MainWindow", "Función 4"))
        self.transferf5.setText(_translate("MainWindow", "Función 5"))
        self.label.setText(_translate("MainWindow", "Orden"))
        self.label_2.setText(_translate("MainWindow", "Valor"))
        self.addcoefficient.setText(_translate("MainWindow", "Agregar coeficiente"))
        self.importlabel_2.setText(_translate("MainWindow", "Visualización"))
        self.saveamp.setText(_translate("MainWindow", "Gráfico de amplitud"))
        self.savephase.setText(_translate("MainWindow", "Gráfico de fase"))
        self.saveboth.setText(_translate("MainWindow", "Gráfico completo"))
        self.importlabel_3.setText(_translate("MainWindow", "Exportar imagen"))
        self.checkf5.setText(_translate("MainWindow", "Ver Función 5"))
        self.checkf3.setText(_translate("MainWindow", "Ver Función 3"))
        self.checkf1.setText(_translate("MainWindow", "Ver Función 1"))
        self.checkf4.setText(_translate("MainWindow", "Ver Función 4"))
        self.checkf2.setText(_translate("MainWindow", "Ver Función 2"))
        self.importlabel_4.setText(_translate("MainWindow", "Puntos"))
        self.importlabel_6.setText(_translate("MainWindow", "Origen"))
        self.origin1.setText(_translate("MainWindow", "Ecuación"))
        self.origin2.setText(_translate("MainWindow", "Ecuación"))
        self.origin3.setText(_translate("MainWindow", "Ecuación"))
        self.origin4.setText(_translate("MainWindow", "Ecuación"))
        self.origin5.setText(_translate("MainWindow", "Ecuación"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
